pipeline:
  name: feat-5
  identifier: feat5
  projectIdentifier: demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dd
        identifier: dd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: <+input>
        tags: {}
